name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

# cli is in a subdirectory
jobs:
  build-and-test-cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build CLI
      run: cargo build --manifest-path rustlab/cli/Cargo.toml --verbose

    - name: Run CLI Tests
      run: cargo test --manifest-path rustlab/cli/Cargo.toml --verbose
